Add using APP_ROOT_PATH and PLATFORM_PATH vars in install scripts
ostis-apps/ostis-example-app pull request #20
Opened 2020-11-17 16:25 UTC by KovalM

2020-11-18 13:48 UTC, ValikVityaz requested changes

2020-11-18 13:48 UTC, ValikVityaz commented on scripts/install_ostis.sh
> +	cat ../bin/config.ini >> "${PLATFORM_PATH}"/config/sc-web.ini
'..' is replaced everywhere but here. Shouldn't it be `cat "${PLATFORM_PATH}"/sc-machine/bin/config.ini`?

2020-11-18 13:48 UTC, ValikVityaz commented on scripts/clone_subsystems.sh
> +cd ${APP_ROOT_PATH}
```suggestion
cd "${APP_ROOT_PATH}"
```
Should be wrapped in quotes everywhere.

2020-11-18 13:48 UTC, ValikVityaz commented on scripts/clone_subsystems.sh
>      mkdir subsystems
```suggestion
then
	mkdir subsystems
```

2020-11-18 13:48 UTC, ValikVityaz commented on scripts/clone_subsystems.sh
> +    echo "../subsystems" >> "${PLATFORM_PATH}"/repo.path
```suggestion
	echo "../subsystems" >> "${PLATFORM_PATH}"/repo.path
```

2020-11-18 13:48 UTC, ValikVityaz commented on scripts/install_subsystems.sh
```suggestion

```

2020-11-22 19:00 UTC, MikhailSadovsky approved these changes

2020-11-22 23:40 UTC, ValikVityaz commented on scripts/install_ostis.sh
> +if [ -d ${PLATFORM_PATH} ];
```suggestion
if [ -d "${PLATFORM_PATH}" ];
```

2020-11-23 08:24 UTC, ValikVityaz approved these changes

2020-11-23 14:12 UTC, merged